### ISSUE TITLE
rov_control.py has bug during update teleop modes

### ISSUE THREAD

**Issue by yameatmeyourdead** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming#14]
https://github.com/Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming/blob/466035f54044af0f9a213728ecda82e0fb0b703d/src/rov/rov_control/rov_control/rov_control.py#L71-L77

Shouldn't these publishers be swapped?

**Comment by yameatmeyourdead** [comment]
Figured it out: update publishes the respective updating mode as well as a default to the other modes

Why do we not just publish the message that corresponds to out teleop mode?

**Comment by PhocaeaUnitas** [comment]
As of #25, all of the code for the `RovControl` node has been rewritten. This issue is no longer applicable to the current version
