### ISSUE TITLE
GStreamer Pipeline needs to be improved

### ISSUE THREAD

**Issue by yameatmeyourdead** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming#2]
#GStreamer and OpenCV are causing too much CPU load for the Nano
Remove videoconvert and pipe a NV12 or I420 into OpenCV

**Comment by yameatmeyourdead** [comment]
See #4 for proposed implementation

**Comment by Hermanoid** [comment]
How much CPU load we talking?
