### ISSUE TITLE
Redesign Thruster Controller to have dumb controls (priority) and a fancy controller

### ISSUE THREAD

**Issue by yameatmeyourdead** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming#5]
- Continue struggling with fancy controllers?
	- Better for automation tasks
	- Requires lots of testing time
- Implement dumb controls (similar to 2020-2021 season)
	- Might be better for manual control
	- Trickier mapping of controls to 1 joystick
-  Finish implementing and testing BAR02 depth monitoring

**Comment by Hermanoid** [comment]
"fancy controls"?
I mean, I found the existing stuff to be pretty fancy, what with all the control matrices and attitude control. Does "fancy" mean holding the depth constant automatically? I mean... it would be really nice to try it without that feature, but with all of our neutral buoyancy I think manually managing depth would be super difficult

**Comment by yameatmeyourdead** [comment]
Fancy controls was referring the the complicated control matrices for attitude and linear velocity control.

It is probably smart to just have automatic depth control as this will be fairly trivial to implement in a PID controller.

Dumb controls would just be direct mapping of joystick to thruster output (rather than the setpoint of a Feedback Controller). This is easily accomplished with some vector math and normalization to get full thrust output. Although this method retains the challenge of mapping 6 DOF to a 4 DOF controller (necessitating translation/rotation modes)

**Comment by Hermanoid** [comment]
Okay, by this "setpoint of a Feedback Controller" you're alluding to the
system you proposed to hold attitude constant while translating linearly
and vice versa. In that case, starting with "dumb" controls sounds like a
no-brainer.

**Comment by yameatmeyourdead** [comment]
Need to run a test to determine accelerometer bias for PID controller stability. Requires works-like testing rig that has mounted BNO to determine integral windup.
