### ISSUE TITLE
Finish implementation of ROV Statistics

### ISSUE THREAD

**Issue by yameatmeyourdead** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming#7]
Implement the following features:
- CPU/RAM usage
	- psutil
- CPU/Package Temps
	- psutil doesn't seem to work for the jetson (find something different)
- Temperature
	- BNO055 is decently good for this
- Power/Voltage
	- Connect to BMR4800116/005
		- I2C bus wasnt working last I checked
- Good GUI Display of aforementioned information

**Comment by Hermanoid** [comment]
I usually scrape the output of `sensors` for CPU temp info, perhaps that would also work on the jetson

**Comment by yameatmeyourdead** [comment]
See: https://www.commandlinux.com/man-page/man1/sensors.1.html
See: https://stackoverflow.com/questions/478898/how-do-i-execute-a-command-and-get-the-output-of-the-command-within-c-using-po
BMR4800116/005 I2C connection not working. We'll look into this later, ignore that task
Ignore GUI display for now
