### ISSUE TITLE
Change Driverstation to Raylib backend

### ISSUE THREAD

**Issue by yameatmeyourdead** [Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming#8]
- Make GUI pretty
- Orientation Display
- Joystick input display
- 4 Camera streams
- E-stop
- Statistics display
- SSH session
- ROS2 Logs monitoring

**Comment by Hermanoid** [comment]
Is Raylib a client-side thing, or is this going to involve streaming a (somehow interactive) video feed to the user?
Also... I'm guessing this is another alternative to the dozens of other GUI platforms discussed? If so, it seems like a decent choice, but how did we arrive at it?

**Comment by yameatmeyourdead** [comment]
> Is Raylib a client-side thing, or is this going to involve streaming a (somehow interactive) video feed to the user? Also... I'm guessing this is another alternative to the dozens of other GUI platforms discussed? If so, it seems like a decent choice, but how did we arrive at it?

Raylib is a rendering API; client-side to the driverstation.

Previously we were using flask, a python module that allows you to run a webserver that interfaces with python code easily. There were significant design challenges in using this module because of some technical limitations with how many data streams we could have (thats why there is only space for 3 cameras).
We toyed with the idea of using another API such as SDL/SFML, but Cameron likes the look of Raylib and its not a terribly difficult (or obscure) API to get into.

**Comment by yameatmeyourdead** [comment]
See #17
